name: Update today xin wen lian bo

on:
  workflow_dispatch:
  schedule:
    # 东八区 (UTC+8), 所以要-8小时
    - cron: '30 15 * * *'

# permissions:
#   contents: read

jobs:
  update:
    name: Update today xin wen lian bo
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - name: npm install
        run: npm install
      - name: npm run index
        run: npm run index
