name: Update today xin wen lian bo

on:
  workflow_dispatch:
  schedule:
    # 东八区 (UTC+8), 所以要-8小时
    - cron: '00 12 * * *'

# permissions:
#   contents: read

jobs:
  update:
    name: Update today xin wen lian bo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run index
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3
#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: 'npm'
#           cache-dependency-path: './package-lock.json'
#       - name: npm install
#         run: npm install
#       - name: npm run index
#         run: npm run index
