name: Update today xin wen lian bo

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *' # once a day at 19:40 UTC / 11:40 PST

# permissions:
#   contents: read

jobs:
  update:
    name: Update today xin wen lian bo
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: npm i
        run: npm i
      - name: node index.js
        run: node index.js
